//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebsiteVpProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int userId { get; set; }
        public string userFirstName { get; set; }
        public string userLastName { get; set; }
        public string userAddress { get; set; }
        public string userCountry { get; set; }
        public string userProvience { get; set; }
        public string userCity { get; set; }
        public string userPostelcode { get; set; }
        public string userEmail { get; set; }
        public string userPhone { get; set; }
        public string userPassword { get; set; }
    }
}
